name: meet_interface
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.1.beta <4.0.0'

dependencies:
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.1
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path_provider: ^2.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/No_camera.png
